server:
  port: 8011

spring:
  application:
    name: product-service

  datasource:
    url: jdbc:mysql://localhost/product_prod_db
    username: prod_user
    password: prod_pass

logging:
  level:
    root: INFO

custom:
  message: "PRODUCT-SERVICE - PROD ENVIRONMENT"
