server:
  port: 8007

spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:mysql://localhost/payment_stage_db
    username: stage_user
    password: stage_pass

logging:
  level:
    root: INFO

custom:
  message: "PAYMENT-SERVICE - STAGE ENVIRONMENT"
