server:
  port: 8022

spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:mysql://localhost/inventory_stage_db
    username: stage_user
    password: stage_pass

logging:
  level:
    root: INFO

custom:
  message: "INVENTORY-SERVICE - STAGE ENVIRONMENT"
