server:
  port: 8016

spring:
  application:
    name: customer-service

  datasource:
    url: jdbc:mysql://localhost/customer_stage_db
    username: stage_user
    password: stage_pass

logging:
  level:
    root: INFO

custom:
  message: "CUSTOMER-SERVICE - STAGE ENVIRONMENT"
